# Generated by Django 6.0.2 on 2026-08-17 22:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nursery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text='Hardware identifier, e.g. ESP32-001 or MAC address based ID.', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Human-readable nickname for the unit.', max_length=100)),
                ('api_key_hash', models.CharField(editable=False, max_length=128)),
                ('api_key_prefix', models.CharField(db_index=True, editable=False, max_length=16)),
                ('firmware_version', models.CharField(default='1.0.0', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nursery_zone', models.ForeignKey(blank=True, help_text='Nursery zone where this hardware unit is deployed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='nursery.nurseryzone')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['device_id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_on_threshold', models.FloatField(default=30.0, help_text='Soil moisture percentage below which irrigation turns ON.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('pump_off_threshold', models.FloatField(default=50.0, help_text='Soil moisture percentage above which irrigation turns OFF.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('reading_interval_seconds', models.PositiveIntegerField(default=2, help_text='Sensor sampling period in seconds.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)])),
                ('upload_interval_seconds', models.PositiveIntegerField(default=10, help_text='Telemetry upload period to server in seconds.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)])),
                ('automatic_mode', models.BooleanField(default=True, help_text='Enable autonomous local threshold-based relay actuation on ESP32.')),
                ('max_pump_runtime_seconds', models.PositiveIntegerField(default=30, help_text='Maximum continuous pump runtime to prevent flood/dry-run.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='devices.device')),
            ],
            options={
                'verbose_name': 'Device Setting',
                'verbose_name_plural': 'Device Settings',
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssi', models.IntegerField(blank=True, help_text='Wi-Fi Signal strength in dBm (e.g. -65).', null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=30)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('operational_state', models.CharField(default='IDLE', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='devices.device')),
            ],
            options={
                'verbose_name': 'Device Status',
                'verbose_name_plural': 'Device Statuses',
            },
        ),
    ]
