# Generated by Django 6.0.2 on 2026-10-02 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesetting',
            name='fan_off_temperature',
            field=models.FloatField(default=25.0, help_text='Air temperature (°C) below which ventilation fan turns OFF.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(80.0)]),
        ),
        migrations.AddField(
            model_name='devicesetting',
            name='fan_on_humidity',
            field=models.FloatField(default=85.0, help_text='Air relative humidity (%) above which ventilation fan turns ON.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='devicesetting',
            name='fan_on_temperature',
            field=models.FloatField(default=30.0, help_text='Air temperature (°C) above which ventilation fan turns ON.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(80.0)]),
        ),
        migrations.AlterField(
            model_name='devicesetting',
            name='automatic_mode',
            field=models.BooleanField(default=True, help_text='Enable autonomous local threshold-based relay actuation on ESP32/ESP8266.'),
        ),
    ]
