# Generated by Django 6.0.2 on 2026-08-17 22:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nursery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the nursery.', max_length=100)),
                ('code', models.CharField(db_index=True, help_text='Unique uppercase code e.g. NURSERY-NORTH-01', max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text='Physical address or GPS coordinates.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nursery',
                'verbose_name_plural': 'Nurseries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NurseryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='nursery.nursery')),
            ],
            options={
                'verbose_name': 'Nursery Zone',
                'verbose_name_plural': 'Nursery Zones',
                'ordering': ['nursery', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SeedlingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(db_index=True, help_text='Unique batch identification code, e.g. BATCH-2026-TOM-001', max_length=50, unique=True)),
                ('plant_name', models.CharField(help_text='Common name e.g. Tomato', max_length=100)),
                ('species', models.CharField(blank=True, help_text='Scientific name e.g. Solanum lycopersicum', max_length=100)),
                ('variety', models.CharField(blank=True, help_text='Cultivar / Variety e.g. San Marzano', max_length=100)),
                ('planting_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_transplant_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('SEEDED', 'Seeded'), ('GERMINATING', 'Germinating'), ('GROWING', 'Growing'), ('READY', 'Ready for Transplant'), ('TRANSPLANTED', 'Transplanted'), ('ARCHIVED', 'Archived')], default='GROWING', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('care_instructions', models.TextField(blank=True, help_text='Customer care instructions rendered on public QR page.')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='seedlings/photos/')),
                ('qr_token', models.CharField(db_index=True, editable=False, help_text='Secret UUID token for public QR code customer access.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seedling_batches', to='nursery.nursery')),
                ('nursery_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seedling_batches', to='nursery.nurseryzone')),
            ],
            options={
                'verbose_name': 'Seedling Batch',
                'verbose_name_plural': 'Seedling Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='nurseryzone',
            constraint=models.UniqueConstraint(fields=('nursery', 'code'), name='unique_nursery_zone_code'),
        ),
    ]
