# Generated by Django 6.0.2 on 2026-08-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_alerts',
            field=models.BooleanField(default=True, help_text='Enable to display and grant access to System Alerts & Warnings.', verbose_name='System Alerts & Warnings'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_batches',
            field=models.BooleanField(default=True, help_text='Enable to display and grant access to Seedling Batches & QR Passports.', verbose_name='Seedling Batches'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_dashboard',
            field=models.BooleanField(default=True, help_text='Enable to display and grant access to the Live Interactive Dashboard.', verbose_name='Live Interactive Dashboard'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_irrigation',
            field=models.BooleanField(default=True, help_text='Enable to display and grant access to Irrigation Settings.', verbose_name='Irrigation Settings'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_nurseries',
            field=models.BooleanField(default=True, help_text='Enable to display and grant access to Nurseries management.', verbose_name='Nurseries'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_telemetry',
            field=models.BooleanField(default=True, help_text='Enable to display and grant access to Sensor Telemetry Readings.', verbose_name='Sensor Telemetry Readings'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_zones',
            field=models.BooleanField(default=True, help_text='Enable to display and grant access to Nursery Zones management.', verbose_name='Nursery Zones'),
        ),
    ]
