# Generated by Django 6.0.2 on 2026-08-17 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_SOIL_MOISTURE', 'Low Soil Moisture'), ('HIGH_SOIL_TEMPERATURE', 'High Soil Temperature'), ('DEVICE_OFFLINE', 'Device Offline'), ('SENSOR_ERROR', 'Sensor Reading Error'), ('PUMP_TIMEOUT', 'Pump Safety Timeout')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, default='WARNING', max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.device')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'is_resolved', 'alert_type'], name='alert_dev_status_type_idx')],
            },
        ),
    ]
