# Generated by Django 6.0.2 on 2026-08-17 22:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_temperature', models.FloatField(help_text='Soil temperature in degrees Celsius (DS18B20).', validators=[django.core.validators.MinValueValidator(-20.0), django.core.validators.MaxValueValidator(80.0)])),
                ('soil_moisture', models.FloatField(help_text='Calibrated soil moisture percentage (0-100%).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('soil_moisture_raw', models.PositiveIntegerField(help_text='Raw 12-bit ADC reading from capacitive sensor (0-4095).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4095)])),
                ('pump_status', models.BooleanField(help_text='Actuation state of the 5V water pump relay (True=ON, False=OFF).')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp recorded by the backend server.')),
                ('device_timestamp', models.DateTimeField(blank=True, help_text='Optional timestamp sent directly by device RTC.', null=True)),
                ('device', models.ForeignKey(help_text='Originating ESP32 device.', on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.device')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['device', 'received_at'], name='sensor_dev_received_idx'), models.Index(fields=['-received_at'], name='sensor_received_desc_idx')],
            },
        ),
    ]
