# Generated by Django 6.0.2 on 2026-10-02 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='air_humidity',
            field=models.FloatField(blank=True, help_text='Ambient air relative humidity percentage (DHT22).', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='air_temperature',
            field=models.FloatField(blank=True, help_text='Ambient air temperature in degrees Celsius (DHT22).', null=True, validators=[django.core.validators.MinValueValidator(-40.0), django.core.validators.MaxValueValidator(80.0)]),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='fan_status',
            field=models.BooleanField(default=False, help_text='Actuation state of the ventilation/cooling fan relay (True=ON, False=OFF).'),
        ),
    ]
